---
- name: "Config: Debug pkg_debug={{ pkg_debug }}"
  vars:
    msg: |-
      pkg_owner: {{ pkg_owner }}
      pkg_group: {{ pkg_group }}
      pkg_backup_conf: {{ pkg_backup_conf }}
      pkg_default_repo_template: {{ pkg_default_repo_template }}
      pkg_default_repo_conf:
        {{ pkg_default_repo_conf | to_nice_yaml(indent=2) | indent(2) }}
      pkg_repos_template: {{ pkg_repos_template }}
      pkg_repos_conf:
        {{ pkg_repos_conf | to_nice_yaml(indent=2) | indent(2) }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: pkg_debug | bool

- name: "Config: Configure /etc/pkg/FreeBSD.conf"
  ansible.builtin.template:
    src: "{{ pkg_default_repo_template }}"
    dest: /etc/pkg/FreeBSD.conf
    owner: "{{ pkg_owner }}"
    group: "{{ pkg_group }}"
    mode: "0644"
    backup: "{{ pkg_backup_conf }}"
  loop: "{{ pkg_default_repo_conf }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create /usr/local/etc/pkg/repos/*
  when: pkg_repos_conf | length > 0
  block:

    - name: "Config: Create directories"
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ pkg_owner }}"
        group: "{{ pkg_group }}"
        mode: "0755"
      loop:
        - /usr/local/etc/pkg
        - /usr/local/etc/pkg/repos

    - name: "Config: Configure /usr/local/etc/pkg/repos"
      ansible.builtin.template:
        src: "{{ pkg_repos_template }}"
        dest: /usr/local/etc/pkg/repos/{{ item.name }}.conf
        owner: "{{ pkg_owner }}"
        group: "{{ pkg_group }}"
        mode: "0644"
        backup: "{{ pkg_backup_conf }}"
      loop: "{{ pkg_repos_conf }}"
      loop_control:
        label: "{{ item.name }}"

# EOF
