---
- name: "Sanity: Test collection community_general minimal version {{ pkg_version_community_general }}"
  ansible.builtin.assert:
    that: _version is version(pkg_version_community_general, '>=')
    fail_msg: >
      [ERR] community_general minimal version is {{ pkg_version_community_general }}
      Found {{ _version }}
  vars:
    _version: "{{ lookup('community.general.collection_version', 'community.general') }}"
  when: pkg_sanity_version_community_general | bool

# EOF
