---

- name: "vars: Debug for {{ ansible_architecture }}"
  vars:
    msg: |-
      pkg_list
      {{ pkg_list|to_nice_yaml }}
      pkg_dict
      {{ pkg_dict|to_nice_yaml }}
      pkg_dict_select
      {{ pkg_dict_select|to_yaml }}

      pkg_list {{ ansible_architecture }}
      {{ lookup('vars', 'pkg_list_' + ansible_architecture)|default([])|to_nice_yaml }}
      pkg_dict {{ ansible_architecture }}
      {{ lookup('vars', 'pkg_dict_' + ansible_architecture)|default([])|to_nice_yaml }}
  ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
  when: pkg_debug|bool

- name: "vars: Select all packages for {{ ansible_architecture }}"
  ansible.builtin.set_fact:
    pkg_dict: "{{ pkg_dict + lookup('vars', 'pkg_dict_' + ansible_architecture)|default([]) }}"
    pkg_list: "{{ pkg_list + lookup('vars', 'pkg_list_' + ansible_architecture)|default([]) }}"
  when: pkg_select_all|bool

- name: "vars: Select list of packages for {{ ansible_architecture }}"
  ansible.builtin.set_fact:
    pkg_list: "{{ pkg_list + lookup('vars', 'pkg_dict_' + ansible_architecture)|json_query(query) }}"
  loop: "{{ pkg_dict_select }}"
  vars:
    query: "[?pkglist=='{{ item.list }}'].packages"
  when: item.enabled

- name: "vars: Default emply, flatten, unique, and sort packages"
  ansible.builtin.set_fact:
    pkg_list: "{{ pkg_list|default([])|flatten|unique|sort }}"

# EOF
...
